baseURL = "https://lsnotes.com/"
languageCode = "en-us"
# [en, zh-cn, fr, pl, ...] determines default content language
defaultContentLanguage = "en"
theme = "hugo-tania"

# website title
title = "> ls notes/"
paginate = 6

[params]
  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  siteName = "ls notes"
  siteDesc = "Alexander Cherepanov's Personal blog."
  author = "Alexander Cherepanov"

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    email = "alex@lsnotes.com"
    github = "https://github.com/alexintech"
    linkedin = "https://linked.in/alexandr-cherepanov-4875ab108"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    lineNos = true
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark.renderer]
    # whether to use HTML tags directly in the document
    unsafe = true

# Permalinks config (https://gohugo.io/content-management/urls/#permalinks)
[permalinks]
  posts = ":year/:month/:filename"

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
[[menu.header]]
  name = "Articles"
  url = "/articles/"
[[menu.footer]]
  name = "RSS"
  url = "/index.xml"
